In [1]:
# numpy >> numerical python
# 2005 by Travis OLiphant

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
lis=[1,2,3,'pankaj kumawat', True, 1,5]

In [9]:
type(lis)

list

In [10]:
# numpy stores the data in an array: 
# an array is a container used to store the data of same data type

In [11]:
# why numpy: 
# computation is fast >> due to array>> contigues memory location
# mathematical computaion provide

In [12]:
l=[1,2,3,4,5]

In [14]:
arr=np.array(l)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
l=[1,2,3,4,5.3]
arr=np.array(l)   # all become float

In [17]:
arr

array([1. , 2. , 3. , 4. , 5.3])

In [18]:
l=[1,2,3,4,5.3, 'pankaj']
arr=np.array(l)  # all become string

In [19]:
arr

array(['1', '2', '3', '4', '5.3', 'pankaj'], dtype='<U32')

In [20]:
# array store homogenous data

In [21]:
type(arr)

numpy.ndarray

In [22]:
arr.ndim

1

In [23]:
arr1=np.array([[1,2,3],[4,5,6]])

In [24]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr1.ndim

2

In [27]:
mat=np.matrix(([1,2,3,4]))    # matrix is a specialised array and it will be always 2 dimension

In [28]:
mat

matrix([[1, 2, 3, 4]])

In [29]:
type(mat)

numpy.matrix

In [30]:
np.matrix([[[1,2],[3,4],[5,6]]])

ValueError: matrix must be 2-dimensional

In [39]:
np.array(mat)

array([[1, 2, 3, 4]])

In [31]:
# more way to convert array
l=[1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

In [32]:
mat

matrix([[1, 2, 3, 4]])

In [33]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [34]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [38]:
np.asanyarray(mat)   # can't convert matrix into array

matrix([[1, 2, 3, 4]])

In [1]:
# np.array() and np.asarray convert into array either it is not array or subclass of array(matrix)
#np.asanyarray() convert in array only that is not array (can't convert matrix in array)

In [3]:
t=([1,2,3], [4,5,6])  #tuple ot array

In [4]:
type(t)

tuple

In [5]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
l=[1,2,3,4,5]
arr=np.array(l)

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr[0]

1

In [28]:
arr[0]=100

In [29]:
arr     # array is mutable

array([100,   2,   3,   4,   5])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [31]:
a=arr   #shallow copy>> change in arr also lead to change in a

In [32]:
a

array([100,   2,   3,   4,   5])

In [33]:
arr[1]=10000

In [34]:
a  

array([  100, 10000,     3,     4,     5])

In [35]:
b=arr.copy() # deep copy

In [36]:
arr[2]=4000

In [37]:
b

array([  100, 10000,     3,     4,     5])

In [38]:
# we learned to create an arrya>> np.array, np.asarray, np.asanyarray,deep copy, shallow copy

In [39]:
# multiple ways to generate array

In [42]:
arr1=np.fromfunction(lambda i, j: i==j, (3,3)) # Construct an array by executing a function over each coordinate.

In [44]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
arr1.ndim

2

In [46]:
arr1.shape   # shape of arry

(3, 3)

In [47]:
arr1.size      # numberr of elms in array

9

In [48]:
arr2=np.fromfunction(lambda i, j: i*j, (3,3))

In [49]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
for i in range(5): 
    print(i)

0
1
2
3
4


In [51]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [57]:
(i for i in range(5))

<generator object <genexpr> at 0x0000023DFF2E20C0>

In [58]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [60]:
iterable=(i for i in range(5))

In [63]:
np.fromiter(iterable, int)  # Create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [85]:
list=[i**3 for i in range(5)]
iterator=iter(list)
np.fromiter(iterator, int)

array([ 0,  1,  8, 27, 64])

In [64]:
np.fromstring('22 23 24', sep=" ")

array([22., 23., 24.])

In [65]:
np.fromstring('22,23,24', sep=",")  # values should be numerical

array([22., 23., 24.])

In [69]:
np.fromstring('pankaj kumar smpr', sep=" ")  # it not work for character string so use split method

C:\Users\91830\AppData\Local\Temp\ipykernel_12964\1020980453.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('pankaj kumar smpr', sep=" ")


array([], dtype=float64)

In [72]:
# for string characater you hve to use split
string='pankaj kumar smpr'
string1=string.split(' ')
np.array(string1)

array(['pankaj', 'kumar', 'smpr'], dtype='<U6')

In [74]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
range(10)

range(0, 10)

In [82]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [84]:
list(range(1,10,2.4)) # not float jump but numpy support

TypeError: 'float' object cannot be interpreted as an integer

In [77]:
# otherr methods of numpy>>  to generate sequnce of numbers
np.arange(1,10,0.8)  # Return evenly spaced values within a given interval.

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [78]:
np.linspace(1,5,10)  # Return evenly spaced numbers over a specified interval.
# give me 10 numberrs between 1 to 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [79]:
np.logspace(1,5,10)  # bydefault log 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [80]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])