In [1]:
import numpy as np

In [3]:
a=np.zeros(5) # Return a new array of given shape and type, filled with zeros.

In [4]:
a.ndim

1

In [5]:
b=np.zeros((3,4))

In [6]:
b.ndim

2

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# np.twos(2)   # does not exist

AttributeError: module 'numpy' has no attribute 'twos'

In [10]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [12]:
arr=np.zeros((3,4))

In [13]:
arr.ndim

2

In [15]:
# 3 dimensional array: 
arr=np.zeros((1,2,4))

In [16]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr.ndim

3

In [18]:
arr=np.zeros((1,1,3,4))

In [19]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [22]:
arr=np.zeros((1,1,1,3,4))

In [23]:
arr.ndim

5

In [24]:
arr=np.ones((3,4))

In [25]:
arr.ndim

2

In [26]:
arr.shape

(3, 4)

In [27]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [30]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [31]:
arr-2

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [32]:
np.eye(5)  # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
np.empty((3,4))  # Return a new array of given shape and type, without initializing entries.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# optional topic: random module

import random
random.choice((1,2,3,4,5))

3

In [44]:
random.choice('pankaj')

'p'

In [46]:
random.randrange(1,19)

11

In [48]:
random.random()   # random no is generated between [0,1)

0.5583224765279904

In [49]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [50]:
random.shuffle(lis)

In [51]:
lis

[1, 4, 3, 2, 5]

In [52]:
random.uniform(7,14)

11.014523644363475

In [54]:
# to have random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [55]:
np.random.random_sample()

0.7290213038120837

In [56]:
np.random.random_sample(5)

array([0.5698029 , 0.67427026, 0.44358759, 0.75182505, 0.59744243])

In [57]:
np.random.random_sample((5,))

array([0.25635782, 0.58490973, 0.944372  , 0.48152672, 0.42133991])

In [58]:
np.random.rand(1)

array([0.39423457])

In [61]:
np.random.rand(2,3)

array([[0.84012545, 0.54300374, 0.17754525],
       [0.25022894, 0.06500792, 0.51168774]])

In [62]:
np.random.randn(2,3)   # normal distribution data

array([[ 1.14099465, -0.878913  , -1.89306585],
       [-1.23824451,  0.12516442, -0.37816557]])

In [64]:
 arr=np.random.randint(1,5,size=(3,4))

In [65]:
arr

array([[4, 1, 2, 3],
       [1, 3, 1, 4],
       [4, 4, 4, 3]])

In [66]:
arr.ndim

2

In [67]:
arr.shape

(3, 4)

In [68]:
arr.size

12

In [70]:
arr

array([[4, 1, 2, 3],
       [1, 3, 1, 4],
       [4, 4, 4, 3]])

In [72]:
# reshaping the array: 
arr1=arr.reshape(2,6)  # array size wiil no change. alwaays reshape paremeter should be multiplicattion jof origional array size

In [73]:
arr1

array([[4, 1, 2, 3, 1, 3],
       [1, 4, 4, 4, 4, 3]])

In [74]:
arr1.size

12

In [75]:
arr

array([[4, 1, 2, 3],
       [1, 3, 1, 4],
       [4, 4, 4, 3]])

In [76]:
arr.size

12

In [77]:
arr.reshape(6,2)

array([[4, 1],
       [2, 3],
       [1, 3],
       [1, 4],
       [4, 4],
       [4, 3]])

In [79]:
arr.reshape(2,5) # 2*5=10 

ValueError: cannot reshape array of size 12 into shape (2,5)

In [80]:
# case when you don't know in reshape what should be the column count

arr.reshape(4,-1)

array([[4, 1, 2],
       [3, 1, 3],
       [1, 4, 4],
       [4, 4, 3]])

In [81]:
arr.reshape(2,-34567)

array([[4, 1, 2, 3, 1, 3],
       [1, 4, 4, 4, 4, 3]])

In [84]:
# case when you know only column count but do'nt know row count
arr1=arr.reshape(-1,3)

In [85]:
arr1.size

12

In [86]:
arr.reshape(12,-233)

array([[4],
       [1],
       [2],
       [3],
       [1],
       [3],
       [1],
       [4],
       [4],
       [4],
       [4],
       [3]])

In [89]:
arr.reshape(12,-233).base # to see the origional array

array([[4, 1, 2, 3],
       [1, 3, 1, 4],
       [4, 4, 4, 3]])

In [90]:
arr.reshape(2,2,3)

array([[[4, 1, 2],
        [3, 1, 3]],

       [[1, 4, 4],
        [4, 4, 3]]])

In [91]:
arr.reshape(1,2,2,3)

array([[[[4, 1, 2],
         [3, 1, 3]],

        [[1, 4, 4],
         [4, 4, 3]]]])

In [92]:
arr.reshape(1,2,2,3).ndim

4

In [93]:
arr.reshape(4,3,1) # 3 raws 1 column repeated 4 times in the third dimension

array([[[4],
        [1],
        [2]],

       [[3],
        [1],
        [3]],

       [[1],
        [4],
        [4]],

       [[4],
        [4],
        [3]]])

In [94]:
# conditions on array: 

arr1=np.random.randint(1,10,(5,6))

In [95]:
arr1

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [96]:
arr1.ndim

2

In [97]:
arr1.size

30

In [98]:
arr1>3

array([[ True,  True, False,  True, False,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True,  True],
       [False,  True,  True, False,  True,  True]])

In [99]:
arr1[arr1>3]

array([6, 9, 5, 4, 6, 6, 6, 9, 6, 5, 4, 8, 9, 8, 9, 6, 9, 5, 4, 4, 9, 4])

In [100]:
arr1[arr1<3]

array([1, 1, 1, 1, 1])

In [101]:
# to access elements in the array
arr1[0]

array([6, 9, 3, 5, 1, 4])

In [102]:
arr1[1]

array([6, 6, 6, 9, 1, 6])

In [103]:
arr1[1][0]

6

In [104]:
arr1

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [106]:
arr1[0:3]  

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9]])

In [109]:
arr1[0:3,[0,2]]   # 0 to second row and oth and 2nd column

array([[6, 3],
       [6, 6],
       [5, 3]])

In [110]:
# slocing on both rows and clumn
arr1[0:3,1:3]

array([[9, 3],
       [6, 6],
       [4, 3]])

In [111]:
arr1[0:2, [0,1]]

array([[6, 9],
       [6, 6]])

In [112]:
arr1[0, [1,3]]

array([9, 5])

In [113]:
arr1[2:4, [0,3]]

array([[5, 8],
       [8, 6]])

In [114]:
arr1[2:5]

array([[5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [115]:
arr1[2:5, 0:2]

array([[5, 4],
       [8, 9],
       [1, 4]])

In [116]:
# methamatical opertratnon on two arrray

arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [117]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [118]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [119]:
arr1+arr2  # indexwise element addition

array([[3, 3, 2],
       [3, 3, 4],
       [4, 3, 3]])

In [120]:
arr1-arr2

array([[ 1,  1,  0],
       [ 1, -1,  0],
       [ 0,  1,  1]])

In [121]:
arr1*arr2 # index wise multiplication

array([[2, 2, 1],
       [2, 2, 4],
       [4, 2, 2]])

In [122]:
arr1/arr2  # index wise division

array([[2. , 2. , 1. ],
       [2. , 0.5, 1. ],
       [1. , 2. , 2. ]])

In [123]:
# marix multiplication different from index wise multiplicatjion

arr1@arr2   # first way

array([[6, 7, 7],
       [7, 6, 6],
       [8, 8, 8]])

In [124]:
np.dot(arr1,arr2 )  # second way

array([[6, 7, 7],
       [7, 6, 6],
       [8, 8, 8]])

In [126]:
4/0  # in python  division by zero error but in numpy no error

ZeroDivisionError: division by zero

In [125]:
arr1/0

C:\Users\91830\AppData\Local\Temp\ipykernel_8224\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [127]:
# brodcasting

arr=np.zeros((3,4))

In [128]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [130]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [131]:
a=np.array([1,2,3,4])

In [132]:
a

array([1, 2, 3, 4])

In [133]:
a.ndim

1

In [134]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [138]:
a=np.array([[1,2,3,4]])

In [139]:
a

array([[1, 2, 3, 4]])

In [140]:
# Transpose

a.T

array([[1],
       [2],
       [3],
       [4]])

In [141]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [144]:
arr1.T

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [146]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [147]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [148]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [150]:
np.min(arr1)

1

In [151]:
np.max(arr1)

2

In [ ]:
#thanks