In [1]:
import numpy as np

In [2]:
a=np.zeros(5) # Return a new array of given shape and type, filled with zeros.

In [3]:
a.ndim

1

In [4]:
b=np.zeros((3,4))

In [5]:
b.ndim

2

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# np.twos(2)   # does not exist

In [8]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
arr=np.zeros((3,4))

In [10]:
arr.ndim

2

In [11]:
# 3 dimensional array: 
arr=np.zeros((1,2,4))

In [12]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
arr.ndim

3

In [14]:
arr=np.zeros((1,1,3,4))

In [15]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [16]:
arr=np.zeros((1,1,1,3,4))

In [17]:
arr.ndim

5

In [18]:
arr=np.ones((3,4))

In [19]:
arr.ndim

2

In [20]:
arr.shape

(3, 4)

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
arr-2

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [25]:
np.eye(5)  # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
np.empty((3,4))  # Return a new array of given shape and type, without initializing entries.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# optional topic: random module

import random
random.choice((1,2,3,4,5))

5

In [29]:
random.choice('pankaj')

'p'

In [30]:
random.randrange(1,19)

1

In [31]:
random.random()   # random no is generated between [0,1)

0.5792607409884045

In [32]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [33]:
random.shuffle(lis)

In [34]:
lis

[3, 4, 5, 2, 1]

In [35]:
random.uniform(7,14)

11.920150242705496

In [36]:
# to have random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [37]:
np.random.random_sample()

0.7630318932957507

In [38]:
np.random.random_sample(5)

array([0.90545311, 0.4106038 , 0.89569776, 0.49248819, 0.27516714])

In [39]:
np.random.random_sample((5,))

array([0.96381788, 0.09763709, 0.48450738, 0.88811331, 0.63976406])

In [40]:
np.random.rand(1)

array([0.78764432])

In [41]:
np.random.rand(2,3)

array([[0.88332664, 0.50044446, 0.75501007],
       [0.75293901, 0.24921399, 0.85948635]])

In [42]:
np.random.randn(2,3)   # normal distribution data

array([[-1.36936606, -0.67682312, -0.03257644],
       [-2.56695479, -0.67667672, -0.31453267]])

In [43]:
 arr=np.random.randint(1,5,size=(3,4))

In [44]:
arr

array([[1, 2, 4, 4],
       [1, 1, 4, 2],
       [3, 1, 1, 3]])

In [45]:
arr.ndim

2

In [46]:
arr.shape

(3, 4)

In [47]:
arr.size

12

In [48]:
arr

array([[1, 2, 4, 4],
       [1, 1, 4, 2],
       [3, 1, 1, 3]])

In [49]:
# reshaping the array: 
arr1=arr.reshape(2,6)  # array size wiil no change. alwaays reshape paremeter should be multiplicattion jof origional array size

In [50]:
arr1

array([[1, 2, 4, 4, 1, 1],
       [4, 2, 3, 1, 1, 3]])

In [51]:
arr1.size

12

In [52]:
arr

array([[1, 2, 4, 4],
       [1, 1, 4, 2],
       [3, 1, 1, 3]])

In [53]:
arr.size

12

In [54]:
arr.reshape(6,2)

array([[1, 2],
       [4, 4],
       [1, 1],
       [4, 2],
       [3, 1],
       [1, 3]])

In [55]:
arr.reshape(2,5) # 2*5=10 

ValueError: cannot reshape array of size 12 into shape (2,5)

In [ ]:
# case when you don't know in reshape what should be the column count

arr.reshape(4,-1)

array([[4, 1, 2],
       [3, 1, 3],
       [1, 4, 4],
       [4, 4, 3]])

In [ ]:
arr.reshape(2,-34567)

array([[4, 1, 2, 3, 1, 3],
       [1, 4, 4, 4, 4, 3]])

In [ ]:
# case when you know only column count but do'nt know row count
arr1=arr.reshape(-1,3)

In [ ]:
arr1.size

12

In [ ]:
arr.reshape(12,-233)

array([[4],
       [1],
       [2],
       [3],
       [1],
       [3],
       [1],
       [4],
       [4],
       [4],
       [4],
       [3]])

In [ ]:
arr.reshape(12,-233).base # to see the origional array

array([[4, 1, 2, 3],
       [1, 3, 1, 4],
       [4, 4, 4, 3]])

In [ ]:
arr.reshape(2,2,3)

array([[[4, 1, 2],
        [3, 1, 3]],

       [[1, 4, 4],
        [4, 4, 3]]])

In [ ]:
arr.reshape(1,2,2,3)

array([[[[4, 1, 2],
         [3, 1, 3]],

        [[1, 4, 4],
         [4, 4, 3]]]])

In [ ]:
arr.reshape(1,2,2,3).ndim

4

In [ ]:
arr.reshape(4,3,1) # 3 raws 1 column repeated 4 times in the third dimension

array([[[4],
        [1],
        [2]],

       [[3],
        [1],
        [3]],

       [[1],
        [4],
        [4]],

       [[4],
        [4],
        [3]]])

In [ ]:
# conditions on array: 

arr1=np.random.randint(1,10,(5,6))

In [ ]:
arr1

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

30

In [ ]:
arr1>3

array([[ True,  True, False,  True, False,  True],
       [ True,  True,  True,  True, False,  True],
       [ True,  True, False,  True, False,  True],
       [ True,  True, False,  True,  True,  True],
       [False,  True,  True, False,  True,  True]])

In [ ]:
arr1[arr1>3]

array([6, 9, 5, 4, 6, 6, 6, 9, 6, 5, 4, 8, 9, 8, 9, 6, 9, 5, 4, 4, 9, 4])

In [ ]:
arr1[arr1<3]

array([1, 1, 1, 1, 1])

In [ ]:
# to access elements in the array
arr1[0]

array([6, 9, 3, 5, 1, 4])

In [ ]:
arr1[1]

array([6, 6, 6, 9, 1, 6])

In [ ]:
arr1[1][0]

6

In [ ]:
arr1

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [ ]:
arr1[0:3]  

array([[6, 9, 3, 5, 1, 4],
       [6, 6, 6, 9, 1, 6],
       [5, 4, 3, 8, 1, 9]])

In [ ]:
arr1[0:3,[0,2]]   # 0 to second row and oth and 2nd column

array([[6, 3],
       [6, 6],
       [5, 3]])

In [ ]:
# slocing on both rows and clumn
arr1[0:3,1:3]

array([[9, 3],
       [6, 6],
       [4, 3]])

In [ ]:
arr1[0:2, [0,1]]

array([[6, 9],
       [6, 6]])

In [ ]:
arr1[0, [1,3]]

array([9, 5])

In [ ]:
arr1[2:4, [0,3]]

array([[5, 8],
       [8, 6]])

In [ ]:
arr1[2:5]

array([[5, 4, 3, 8, 1, 9],
       [8, 9, 1, 6, 9, 5],
       [1, 4, 4, 3, 9, 4]])

In [ ]:
arr1[2:5, 0:2]

array([[5, 4],
       [8, 9],
       [1, 4]])

In [ ]:
# methamatical opertratnon on two arrray

arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [ ]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [ ]:
arr1+arr2  # indexwise element addition

array([[3, 3, 2],
       [3, 3, 4],
       [4, 3, 3]])

In [ ]:
arr1-arr2

array([[ 1,  1,  0],
       [ 1, -1,  0],
       [ 0,  1,  1]])

In [ ]:
arr1*arr2 # index wise multiplication

array([[2, 2, 1],
       [2, 2, 4],
       [4, 2, 2]])

In [ ]:
arr1/arr2  # index wise division

array([[2. , 2. , 1. ],
       [2. , 0.5, 1. ],
       [1. , 2. , 2. ]])

In [ ]:
# marix multiplication different from index wise multiplicatjion

arr1@arr2   # first way

array([[6, 7, 7],
       [7, 6, 6],
       [8, 8, 8]])

In [ ]:
np.dot(arr1,arr2 )  # second way

array([[6, 7, 7],
       [7, 6, 6],
       [8, 8, 8]])

In [ ]:
4/0  # in python  division by zero error but in numpy no error

ZeroDivisionError: division by zero

In [ ]:
arr1/0

C:\Users\91830\AppData\Local\Temp\ipykernel_8224\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# brodcasting

arr=np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a=np.array([[1,2,3,4]])

In [ ]:
a

array([[1, 2, 3, 4]])

In [ ]:
# Transpose

a.T

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [ ]:
arr1.T

array([[2, 2, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [ ]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [ ]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2

In [ ]:
#thanks