In [18]:
import numpy as np

In [19]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [20]:
arr1

array([[1, 1, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [21]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [22]:
arr1.flatten()  # convert one dimension

array([1, 1, 1, 2, 2, 1, 1, 2, 1])

In [23]:
# Expend dimension: 

arr=np.array([1,2,3,4])

In [24]:
arr

array([1, 2, 3, 4])

In [25]:
arr.ndim

1

In [26]:
np.expand_dims(arr, axis=0)  # increase the dimension by at provide the axis

array([[1, 2, 3, 4]])

In [27]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [28]:
arr

array([1, 2, 3, 4])

In [29]:
np.expand_dims(arr, axis=1).ndim

2

In [30]:
arr=np.zeros((3,4))

In [31]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
arr.ndim

2

In [33]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [35]:
np.expand_dims(arr, axis=1).ndim

3

In [36]:
a=np.array([[1],[2],[3]])

In [37]:
a

array([[1],
       [2],
       [3]])

In [38]:
a.ndim

2

In [39]:
np.squeeze(a)  # Remove axes of length one from a(decrease by 1 dimension)

array([1, 2, 3])

In [40]:
a

array([[1],
       [2],
       [3]])

In [41]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [42]:
arr1=np.random.randint(1,3,(3,3))


In [43]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [44]:
np.repeat(arr1,2)

array([2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1])

In [45]:
np.repeat(arr1,2,axis=0)

array([[2, 1, 1],
       [2, 1, 1],
       [1, 2, 2],
       [1, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [46]:
np.repeat(arr1,3,axis=1)

array([[2, 2, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 1, 1, 1, 1, 1, 1]])

In [47]:
a

array([[1],
       [2],
       [3]])

In [48]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [49]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [50]:
np.roll(a,-3)

array([[1],
       [2],
       [3]])

In [51]:
np.roll(a,1)

array([[3],
       [1],
       [2]])

In [52]:
c=np.array([[1,2],[3,4],[4,5],[6,7]])

In [53]:
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [54]:
np.roll(c,-1)

array([[2, 3],
       [4, 4],
       [5, 6],
       [7, 1]])

In [55]:
np.roll(c,-2)

array([[3, 4],
       [4, 5],
       [6, 7],
       [1, 2]])

In [56]:
np.roll(c,2)

array([[6, 7],
       [1, 2],
       [3, 4],
       [4, 5]])

In [57]:
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [58]:
np.roll(c,2,axis=0)

array([[4, 5],
       [6, 7],
       [1, 2],
       [3, 4]])

In [59]:
np.roll(c,1,axis=0)

array([[6, 7],
       [1, 2],
       [3, 4],
       [4, 5]])

In [60]:
np.roll(c,1,axis=1)

array([[2, 1],
       [4, 3],
       [5, 4],
       [7, 6]])

In [61]:
np.roll(c,2,axis=1)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [62]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [63]:
arr1+arr2

array([[3, 2, 2],
       [3, 4, 4],
       [4, 3, 2]])

In [64]:
arr1-arr2

array([[ 1,  0,  0],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [65]:
arr1>arr2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [66]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [67]:
~arr1

array([[-3, -2, -2],
       [-2, -3, -3],
       [-3, -2, -2]])

In [ ]:
# Operation of numpy string arrray

In [68]:
d=np.array(['pw', 'skills'])

In [69]:
d

array(['pw', 'skills'], dtype='<U6')

In [70]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [71]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [72]:
np.char.title(d)

array(['Pw', 'Skills'], dtype='<U6')

In [73]:
# mathematical funciton: 
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.84147098],
       [0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.84147098]])

In [74]:
np.cos(arr1)

array([[-0.41614684,  0.54030231,  0.54030231],
       [ 0.54030231, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231,  0.54030231]])

In [75]:
np.tan(arr1)

array([[-2.18503986,  1.55740772,  1.55740772],
       [ 1.55740772, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772]])

In [76]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ]])

In [77]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [78]:
np.power(arr1,3)

array([[8, 1, 1],
       [1, 8, 8],
       [8, 1, 1]], dtype=int32)

In [79]:
np.mean(arr1)

1.4444444444444444

In [80]:
np.max(arr1)

2

In [81]:
np.min(arr1)

1

In [82]:
np.std(arr1)

0.4969039949999533

In [83]:
np.var(arr1)

0.2469135802469136

In [84]:
arr1-arr2

array([[ 1,  0,  0],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [85]:
np.subtract(arr1,arr2)

array([[ 1,  0,  0],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [86]:
arr1*arr2

array([[2, 1, 1],
       [2, 4, 4],
       [4, 2, 1]])

In [87]:
np.multiply(arr1,arr2)

array([[2, 1, 1],
       [2, 4, 4],
       [4, 2, 1]])

In [89]:
np.mod(arr1,arr2)  #Return element-wise remainder of division.

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [90]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [91]:
# sort- search

e=np.array([5,6,1,2])

In [92]:
np.sort(e)

array([1, 2, 5, 6])

In [118]:
f=np.array([5,100,200,6,7,8])

In [119]:
f

array([  5, 100, 200,   6,   7,   8])

In [122]:
sort_f=np.sort(f)

In [124]:
sort_f

array([  5,   6,   7,   8, 100, 200])

In [123]:
np.searchsorted(sort_f,170)  #Find indices where elements should be inserted to maintain order.

5

In [112]:
a=np.array([2,34,17,48,59,30,70])

In [113]:
a

array([ 2, 34, 17, 48, 59, 30, 70])

In [114]:
np.sort(a)

array([ 2, 17, 30, 34, 48, 59, 70])

In [115]:
np.searchsorted(a,51)

6

In [116]:
d=np.sort(a)

In [117]:
np.searchsorted(d,51)

5

In [125]:
f=np.array([1,34,5,6,7,0,0,0,0,0,0,0,0,34,0])

In [126]:
np.count_nonzero(f)

6

In [127]:
f[f>0]

array([ 1, 34,  5,  6,  7, 34])

In [130]:
f

array([ 1, 34,  5,  6,  7,  0,  0,  0,  0,  0,  0,  0,  0, 34,  0])

In [129]:
np.where(f>0)

(array([ 0,  1,  2,  3,  4, 13], dtype=int64),)

In [131]:
np.extract(f>0,f)

array([ 1, 34,  5,  6,  7, 34])

In [132]:
f.byteswap()

array([ 16777216, 570425344,  83886080, 100663296, 117440512,         0,
               0,         0,         0,         0,         0,         0,
               0, 570425344,         0])

In [133]:
# matrix>> 2d array

import numpy.matlib as nm

In [134]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [135]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [139]:
# numpy linear algebra: 

arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(4,5))

In [140]:
arr1@arr2

array([[ 94, 127, 142,  69,  87],
       [101, 141, 150,  62,  88],
       [ 76, 133, 140,  57,  87]])

In [143]:
arr1=np.random.randint(1,10,(3,3))

np.linalg.det(arr1)

175.00000000000006

In [144]:
np.linalg.inv(arr1)

array([[ 0.10285714,  0.12      , -0.17714286],
       [-0.15428571,  0.32      , -0.23428571],
       [ 0.04571429, -0.28      ,  0.36571429]])

In [147]:
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [148]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [152]:
b=np.array([16,8,0])

In [153]:
b

array([16,  8,  0])

In [154]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])