In [2]:
import numpy as np    # numpy deals with arrays and matrix

In [3]:
l=[2,3,4,76,7,8,89]

### ->numpy.array(list): use to convert list to array

In [4]:
arr=np.array(l)    # to convert list to array

In [5]:
arr

array([ 2,  3,  4, 76,  7,  8, 89])

In [6]:
type(arr)     # type is 1 dimentional array

numpy.ndarray

In [7]:
np.array([[3,4],[4,7]])    # 2 dimension array 

array([[3, 4],
       [4, 7]])

In [8]:
l

[2, 3, 4, 76, 7, 8, 89]

### ->numpy.asarray(list): also use to convert list into array

In [9]:
np.asarray(l)

array([ 2,  3,  4, 76,  7,  8, 89])

In [10]:
l

[2, 3, 4, 76, 7, 8, 89]

### ->numpy.asanyarray(list): also use to convert list into array

In [11]:
np.asanyarray(l)

array([ 2,  3,  4, 76,  7,  8, 89])

### ->numpy.matrix(list): is use to convert list into matrix.<br/> 
### ->matrix is the subset(sub class/different form of array) of array.<br/>
### ->matrix is bydefault 2 dimensional

In [12]:
mat=np.matrix(l)

In [13]:
mat

matrix([[ 2,  3,  4, 76,  7,  8, 89]])

In [14]:
type(mat)

numpy.matrix

In [15]:
np.asanyarray(mat)     # it not change because matrix is also the subset of array

matrix([[ 2,  3,  4, 76,  7,  8, 89]])

In [16]:
l

[2, 3, 4, 76, 7, 8, 89]

In [17]:
a=np.asanyarray(l)

In [18]:
a

array([ 2,  3,  4, 76,  7,  8, 89])

In [19]:
c=a         #shallow copy created here,,so variable c also point to the same location of the variable/pointer a

In [20]:
c

array([ 2,  3,  4, 76,  7,  8, 89])

In [21]:
c[0]

2

In [22]:
c[0]=1000

In [23]:
c

array([1000,    3,    4,   76,    7,    8,   89])

In [24]:
a

array([1000,    3,    4,   76,    7,    8,   89])

In [25]:
d=np.copy(a)         # deep copy created here ,, so a and d points to the differrent location

In [26]:
d

array([1000,    3,    4,   76,    7,    8,   89])

In [27]:
a

array([1000,    3,    4,   76,    7,    8,   89])

In [28]:
d[1]

3

In [29]:
d[1]=9000

In [30]:
d

array([1000, 9000,    4,   76,    7,    8,   89])

In [31]:
a

array([1000,    3,    4,   76,    7,    8,   89])

numpy.fromfunction(): 
function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z).<br/>
Syntax : numpy.fromfunction(function, shape,  dtype)

In [32]:
np.fromfunction(lambda i,j: i==j, (3,3))   # 2 dimensional araray

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable=(i*i for i in range(5))

In [35]:
iterable

<generator object <genexpr> at 0x0000023D5D3D1970>

In [36]:
np.fromiter(iterable,float)       

array([ 0.,  1.,  4.,  9., 16.])

In [1]:
import numpy as np

In [3]:
list=[i**3 for i in range(5)]
iterator=iter(list)
np.fromiter(iterator, int)

array([ 0,  1,  8, 27, 64])

In [38]:
np.fromstring('67 78',sep=' ')       #by default value is float

array([67., 78.])

In [39]:
np.fromstring('45,64',int, sep=',')     

array([45, 64])

### numpy.ndim(array) or array.ndim: use to find the dimension of the array.<br/>
### numpy.size(array) or array.size: use to find the total element in the array.<br/>
### numpy.shape(array) or array.shape: use to find the order of the array.<br/>
### array.dtype: use to find the data type of the element present in the array(ans=more byte data type).<br/>


In [40]:
L=[3,45,6,7,5,6,7]

In [41]:
arr1=np.array(L)

In [42]:
arr1

array([ 3, 45,  6,  7,  5,  6,  7])

In [43]:
np.ndim(arr1)       # dimension of aray arr1 is 1

1

In [44]:
arr1.size

7

In [45]:
arr1.shape

(7,)

In [46]:
arr1.dtype

dtype('int32')

In [47]:
arr2=np.array([(3,5,6,7),(4,5,7,8)])

In [48]:
arr2

array([[3, 5, 6, 7],
       [4, 5, 7, 8]])

In [49]:
np.ndim(arr2)

2

In [50]:
np.size(arr2)

8

In [51]:
np.shape(arr2)

(2, 4)

In [52]:
arr2.dtype

dtype('int32')

In [54]:
# np.dtype(arr2)       # error

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr3=np.array([[3.4,6,7,8],[4,5,6,7]])

In [57]:
arr3

array([[3.4, 6. , 7. , 8. ],
       [4. , 5. , 6. , 7. ]])

In [58]:
arr3.dtype

dtype('float64')

## range() vs arange() function

In [59]:
range(5)

range(0, 5)

In [60]:
list(range(3,8))

[3, 4, 5, 6, 7]

In [61]:
list(range(3,8,2))  #  2 is the gape

[3, 5, 7]

In [63]:
# list(range(3.4,8.6))       #error

In [64]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [65]:
np.arange(3,8,2)

array([3, 5, 7])

In [66]:
np.arange(3.4,8.6)

array([3.4, 4.4, 5.4, 6.4, 7.4, 8.4])

In [67]:
np.arange(3.4,8.6,1.3)

array([3.4, 4.7, 6. , 7.3])

In [68]:
list(np.arange(3.4,8.6,1.3))

[3.4, 4.7, 6.0, 7.300000000000001]

In [69]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [70]:
np.logspace(1,5,10)      # bydefault base =10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [71]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [75]:
np.zeros((4,3,2,3))   # 4 dimensuion array

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [76]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [77]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [79]:
on=np.ones((2,3,4))

In [80]:
on+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [81]:
on*4

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [82]:
np.empty((3,4))

array([[1.21656590e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.00238459e-044, 1.16095484e-028, 3.65093134e+233,
        3.35524834e-110],
       [6.32672800e+180, 4.74483502e+170, 2.38435632e-038,
        8.34402701e-309]])

In [83]:
np.eye(4)   # idendity arrya

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.eye(5, dtype=int) 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [92]:
np.random.randn(3,5)   # data mean zero and std one

array([[-0.46559503,  1.28363304, -0.57313855,  1.04675152, -0.96431525],
       [ 2.30790285, -0.08399887,  0.53399723, -1.18040363, -0.34202968],
       [-0.52938634,  0.27775697,  1.20117538, -0.47064967,  1.37012794]])

In [86]:
arr3=np.random.randn(3,5)   # data mean zero and std one

In [6]:
import pandas as pd

In [7]:
pd.DataFrame(data=[[2,4,5],[5,5,3],[76,54,2]], index=['a', 'b','c'],columns=['pankaj','kumawat', 'smpr'])

pankaj  kumawat  smpr
a       2        4     5
b       5        5     3
c      76       54     2

In [88]:
pd.DataFrame(arr3)

0         1         2         3         4
0 -1.217306 -0.680597  0.665042  0.251904  0.928465
1  0.443287  0.163087 -1.540655  0.565832 -0.657614
2  0.267915  0.473934 -0.342018  1.047545 -0.530468

In [90]:
np.random.rand(3,4)

array([[0.10683164, 0.68662908, 0.43362624, 0.95631605],
       [0.58074513, 0.07220337, 0.09310737, 0.43540219],
       [0.99919138, 0.04276107, 0.32571471, 0.48090228]])

In [94]:
np.random.randint(1,100,(3,4))   # range 1  to  100,,,,(3,4) order of array

array([[34, 49, 30, 27],
       [91, 42, 21, 13],
       [41, 43, 22, 59]])

In [102]:
pd.DataFrame(np.random.randint(1,110,(30,40))).to_csv('text.csv')

In [115]:
arr4=np.random.rand(3,4)

In [116]:
arr4

array([[0.62499141, 0.21971361, 0.90893466, 0.50880531],
       [0.89400077, 0.77156021, 0.55617067, 0.85138666],
       [0.5942328 , 0.1234511 , 0.51598913, 0.2352357 ]])

In [123]:
arr4.reshape(6,2)    # change the size of the array not permanant

array([[0.62499141, 0.21971361],
       [0.90893466, 0.50880531],
       [0.89400077, 0.77156021],
       [0.55617067, 0.85138666],
       [0.5942328 , 0.1234511 ],
       [0.51598913, 0.2352357 ]])

In [124]:
arr4

array([[0.62499141, 0.21971361, 0.90893466, 0.50880531],
       [0.89400077, 0.77156021, 0.55617067, 0.85138666],
       [0.5942328 , 0.1234511 , 0.51598913, 0.2352357 ]])

In [126]:
arr5=arr4.reshape(6,-567)      # - means automatically set 2 because not other choice

In [127]:
arr5

array([[0.62499141, 0.21971361],
       [0.90893466, 0.50880531],
       [0.89400077, 0.77156021],
       [0.55617067, 0.85138666],
       [0.5942328 , 0.1234511 ],
       [0.51598913, 0.2352357 ]])

In [129]:
arr5[1]         # second columns

array([0.90893466, 0.50880531])

In [130]:
arr5[1][1]

0.5088053058936258

In [131]:
arr5[2:5]

array([[0.89400077, 0.77156021],
       [0.55617067, 0.85138666],
       [0.5942328 , 0.1234511 ]])

In [132]:
arr5[2:5,1]

array([0.77156021, 0.85138666, 0.1234511 ])

In [134]:
arr6=np.random.randint(1,100,(5,5))

In [135]:
arr6

array([[ 7, 99, 20, 87, 96],
       [54, 42, 31,  1, 98],
       [44, 15, 14, 90, 48],
       [58, 12, 42, 41, 47],
       [63, 74, 84, 67, 21]])

In [136]:
arr6>50

array([[False,  True, False,  True,  True],
       [ True, False, False, False,  True],
       [False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True,  True,  True, False]])

In [139]:
arr6[arr6>50]

array([99, 87, 96, 54, 98, 90, 58, 63, 74, 84, 67])

In [140]:
arr6

array([[ 7, 99, 20, 87, 96],
       [54, 42, 31,  1, 98],
       [44, 15, 14, 90, 48],
       [58, 12, 42, 41, 47],
       [63, 74, 84, 67, 21]])

In [141]:
arr6[2:4,[1,2]]

array([[15, 14],
       [12, 42]])

In [143]:
arr6[0][0]

7

In [144]:
arr6[0][0]=1000

In [145]:
arr6

array([[1000,   99,   20,   87,   96],
       [  54,   42,   31,    1,   98],
       [  44,   15,   14,   90,   48],
       [  58,   12,   42,   41,   47],
       [  63,   74,   84,   67,   21]])

In [148]:
arr7=np.random.randint(1,3,(3,3))
arr8=np.random.randint(1,3,(3,3))

In [149]:
arr7

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [150]:
arr8

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [151]:
arr7+arr8

array([[2, 3, 2],
       [2, 3, 3],
       [3, 3, 4]])

In [152]:
arr7-arr8

array([[ 0,  1,  0],
       [ 0,  1, -1],
       [-1, -1,  0]])

In [153]:
arr7/arr8

array([[1. , 2. , 1. ],
       [1. , 2. , 0.5],
       [0.5, 0.5, 1. ]])

In [154]:
arr7*arr8        # this multipyle not a matrix mumtiplecation its the element multiplecation

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 4]])

In [155]:
arr7@arr8        # this is the matrix multiplecathon

array([[5, 5, 7],
       [5, 5, 7],
       [6, 6, 7]])

In [157]:
arr7/0

C:\Users\pankaj\AppData\Local\Temp\ipykernel_10588\3671141249.py:1: RuntimeWarning: divide by zero encountered in divide
  arr7/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [158]:
arr7+100

array([[101, 102, 101],
       [101, 102, 101],
       [101, 101, 102]])

In [160]:
arr7**2        # square of each elm of the matrix

array([[1, 4, 1],
       [1, 4, 1],
       [1, 1, 4]])

### numpy Brodcasting

In [163]:
arr8=np.zeros((4,4))

In [164]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [165]:
row=np.array([1,2,3,4])

In [166]:
row

array([1, 2, 3, 4])

In [167]:
arr8+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [168]:
row

array([1, 2, 3, 4])

In [171]:
row.ndim

1

In [173]:
row.T      # its not transepose because it is 1 dimensional

array([1, 2, 3, 4])

In [175]:
column=np.array([[1,2,3,4]])

In [176]:
column

array([[1, 2, 3, 4]])

In [177]:
column.ndim

2

In [179]:
column.T           # done

array([[1],
       [2],
       [3],
       [4]])

In [180]:
arr8 + column

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [183]:
arr9=np.random.randint(1,4,(4,4))

In [184]:
arr9

array([[1, 1, 2, 1],
       [3, 1, 1, 2],
       [3, 1, 1, 1],
       [2, 3, 3, 3]])

In [185]:
np.sqrt(arr9)

array([[1.        , 1.        , 1.41421356, 1.        ],
       [1.73205081, 1.        , 1.        , 1.41421356],
       [1.73205081, 1.        , 1.        , 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.73205081]])

In [186]:
np.exp(arr9)

array([[ 2.71828183,  2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [20.08553692,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692, 20.08553692]])

In [187]:
np.log(arr9)

array([[0.        , 0.        , 0.69314718, 0.        ],
       [1.09861229, 0.        , 0.        , 0.69314718],
       [1.09861229, 0.        , 0.        , 0.        ],
       [0.69314718, 1.09861229, 1.09861229, 1.09861229]])

In [188]:
np.log10(arr9)

array([[0.        , 0.        , 0.30103   , 0.        ],
       [0.47712125, 0.        , 0.        , 0.30103   ],
       [0.47712125, 0.        , 0.        , 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.47712125]])

In [ ]:
#thanks