#### Array manipulation- numpy

In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
arr

array([[5, 9, 6, 5],
       [4, 4, 5, 5],
       [3, 3, 3, 9]])

In [4]:
arr.reshape(2,6)   # reshape of the array not permanent

array([[5, 9, 6, 5, 4, 4],
       [5, 5, 3, 3, 3, 9]])

In [5]:
arr.reshape(4,3)

array([[5, 9, 6],
       [5, 4, 4],
       [5, 5, 3],
       [3, 3, 9]])

In [6]:
arr

array([[5, 9, 6, 5],
       [4, 4, 5, 5],
       [3, 3, 3, 9]])

In [9]:
arr.ndim

2

In [12]:
arr1=arr.flatten()     # convert  in one direction       

In [13]:
arr1

array([5, 9, 6, 5, 4, 4, 5, 5, 3, 3, 3, 9])

In [14]:
arr1.ndim

1

In [15]:
arr2=np.array([2,3,4,5,6,8])

In [16]:
arr2

array([2, 3, 4, 5, 6, 8])

In [17]:
arr2.ndim

1

In [19]:
np.expand_dims(arr2,axis=0)    # convert one dimension to 2 dimension ,, axix=0 means towards row

array([[2, 3, 4, 5, 6, 8]])

In [22]:
np.expand_dims(arr2,axis=1)  # axix=1,, means towards column

2

In [23]:
np.expand_dims(arr2,axis=1).ndim

2

In [26]:
arr3=np.random.randint(1,8,(3,4))   # 2 dimensional

In [27]:
arr3     

array([[2, 6, 5, 5],
       [4, 6, 2, 5],
       [4, 5, 2, 4]])

In [28]:
arr3.ndim

2

In [29]:
arr3.squeeze()   # nothing done here

array([[2, 6, 5, 5],
       [4, 6, 2, 5],
       [4, 5, 2, 4]])

In [35]:
data=np.array([[3],[4],[6],[90]])

In [40]:
data

array([[ 3],
       [ 4],
       [ 6],
       [90]])

In [39]:
data.ndim

2

In [41]:
np.squeeze(data)

array([ 3,  4,  6, 90])

In [42]:
np.squeeze(data).ndim

1

In [48]:
arr2

array([2, 3, 4, 5, 6, 8])

In [49]:
arr2.repeat(3)

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 8, 8, 8])

In [52]:
arr2

array([2, 3, 4, 5, 6, 8])

In [54]:
np.roll(arr2,2)       # shift=2

array([6, 8, 2, 3, 4, 5])

In [55]:
np.diag(arr2)

array([[2, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 8]])

#### numpy-Binary Operations

In [57]:
arr4=np.random.randint(1,9,(3,4))
arr5=np.random.randint(1,9,(3,4))

In [58]:
arr4

array([[2, 1, 4, 8],
       [4, 8, 1, 3],
       [6, 2, 1, 7]])

In [59]:
arr5

array([[8, 4, 1, 4],
       [3, 3, 2, 4],
       [4, 7, 3, 6]])

In [60]:
arr4+arr5

array([[10,  5,  5, 12],
       [ 7, 11,  3,  7],
       [10,  9,  4, 13]])

In [61]:
arr4*arr5

array([[16,  4,  4, 32],
       [12, 24,  2, 12],
       [24, 14,  3, 42]])

In [62]:
arr4-arr5

array([[-6, -3,  3,  4],
       [ 1,  5, -1, -1],
       [ 2, -5, -2,  1]])

In [63]:
arr4/arr5

array([[0.25      , 0.25      , 4.        , 2.        ],
       [1.33333333, 2.66666667, 0.5       , 0.75      ],
       [1.5       , 0.28571429, 0.33333333, 1.16666667]])

In [64]:
arr4**arr5

array([[   256,      1,      4,   4096],
       [    64,    512,      1,     81],
       [  1296,    128,      1, 117649]])

In [65]:
arr4 & arr5   # 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [4, 2, 1, 6]])

In [66]:
~arr4

array([[-3, -2, -5, -9],
       [-5, -9, -2, -4],
       [-7, -3, -2, -8]])

In [67]:
arr4 | arr5

array([[10,  5,  5, 12],
       [ 7, 11,  3,  7],
       [ 6,  7,  3,  7]])

In [69]:
arr4>arr5

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [78]:
arr6=np.array(['panKaj', 'kumAWat'])

In [79]:
arr6

array(['panKaj', 'kumAWat'], dtype='<U7')

In [80]:
np.char.upper(arr6)

array(['PANKAJ', 'KUMAWAT'], dtype='<U7')

In [81]:
np.char.title(arr6)

array(['Pankaj', 'Kumawat'], dtype='<U7')

In [82]:
np.char.capitalize(arr6)

array(['Pankaj', 'Kumawat'], dtype='<U7')

#### numpy- mathematical function

In [85]:
arr5

array([[8, 4, 1, 4],
       [3, 3, 2, 4],
       [4, 7, 3, 6]])

In [86]:
np.sin(arr5)

array([[ 0.98935825, -0.7568025 ,  0.84147098, -0.7568025 ],
       [ 0.14112001,  0.14112001,  0.90929743, -0.7568025 ],
       [-0.7568025 ,  0.6569866 ,  0.14112001, -0.2794155 ]])

In [87]:
np.cos(arr5)

array([[-0.14550003, -0.65364362,  0.54030231, -0.65364362],
       [-0.9899925 , -0.9899925 , -0.41614684, -0.65364362],
       [-0.65364362,  0.75390225, -0.9899925 ,  0.96017029]])

In [88]:
np.tan(arr5)

array([[-6.79971146,  1.15782128,  1.55740772,  1.15782128],
       [-0.14254654, -0.14254654, -2.18503986,  1.15782128],
       [ 1.15782128,  0.87144798, -0.14254654, -0.29100619]])

In [89]:
np.tanh(arr5)

array([[0.99999977, 0.9993293 , 0.76159416, 0.9993293 ],
       [0.99505475, 0.99505475, 0.96402758, 0.9993293 ],
       [0.9993293 , 0.99999834, 0.99505475, 0.99998771]])

In [90]:
np.log10(arr5)

array([[0.90308999, 0.60205999, 0.        , 0.60205999],
       [0.47712125, 0.47712125, 0.30103   , 0.60205999],
       [0.60205999, 0.84509804, 0.47712125, 0.77815125]])

In [91]:
np.exp(arr5)

array([[2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 5.45981500e+01],
       [2.00855369e+01, 2.00855369e+01, 7.38905610e+00, 5.45981500e+01],
       [5.45981500e+01, 1.09663316e+03, 2.00855369e+01, 4.03428793e+02]])

In [92]:
np.sqrt(arr5)

array([[2.82842712, 2.        , 1.        , 2.        ],
       [1.73205081, 1.73205081, 1.41421356, 2.        ],
       [2.        , 2.64575131, 1.73205081, 2.44948974]])

In [93]:
np.power(arr5,2)

array([[64, 16,  1, 16],
       [ 9,  9,  4, 16],
       [16, 49,  9, 36]], dtype=int32)

In [94]:
np.mean(arr5)

4.083333333333333

In [95]:
np.median(arr5)

4.0

In [96]:
np.std(arr5)

1.9346977943739831

In [97]:
np.var(arr5)

3.7430555555555554

In [98]:
arr5

array([[8, 4, 1, 4],
       [3, 3, 2, 4],
       [4, 7, 3, 6]])

In [99]:
np.min(arr5)

1

In [101]:
np.max(arr5)

8

### Thankyou