#### sort search and counting function

In [7]:
import numpy as np

In [8]:
arr=np.array([7,55,4,6,77,8,67,3,2,5,566,367,656,])

In [9]:
arr

array([  7,  55,   4,   6,  77,   8,  67,   3,   2,   5, 566, 367, 656])

In [10]:
np.sort(arr)              #Return a sorted copy of an array.

array([  2,   3,   4,   5,   6,   7,   8,  55,  67,  77, 367, 566, 656])

In [15]:
np.searchsorted(arr,55)

6

In [14]:
np.searchsorted(arr,56)       #Find indices where elements should be inserted to maintain order

8

In [16]:
arr1=np.array([7,0,0,6,77,0,0,3,0,5,0,0,656,])

In [17]:
arr1

array([  7,   0,   0,   6,  77,   0,   0,   3,   0,   5,   0,   0, 656])

In [18]:
np.count_nonzero(arr1)   # Counts the number of non-zero values in the array a.

6

In [69]:
arr3=np.array([7,55,4,6,77,8,656,])

In [27]:
np.where(arr3>50)   # giving the index where elements is grater then 50 the arr3

(array([1, 4, 6], dtype=int64),)

In [28]:
arr3

array([  7,  55,   4,   6,  77,   8, 656])

In [30]:
np.extract(arr3>50,arr3)  # Return the elements of an array that satisfy some condition.

array([ 55,  77, 656])

#### numpy -Byte swapping

In [71]:
arr3

array([  7,  55,   4,   6,  77,   8, 656])

In [72]:
arr3.byteswap()

array([  117440512,   922746880,    67108864,   100663296,  1291845632,
         134217728, -1878917120])

#### numpy- copies and views

In [88]:
arr4=np.array([2,3,5,7,56,4,6,7,9])

In [89]:
arr4

array([ 2,  3,  5,  7, 56,  4,  6,  7,  9])

In [90]:
a=np.copy(arr4)   # deep copy created here ,, so a and arr4 points to the differrent location

In [91]:
a

array([ 2,  3,  5,  7, 56,  4,  6,  7,  9])

In [92]:
a[0]

2

In [93]:
a[0]=100

In [94]:
a

array([100,   3,   5,   7,  56,   4,   6,   7,   9])

In [95]:
arr4        # not change in arr4

array([ 2,  3,  5,  7, 56,  4,  6,  7,  9])

In [96]:
b=arr4.view()   #shallow copy created here,,so variable b also point to the same location of the variable/pointer a

In [97]:
b

array([ 2,  3,  5,  7, 56,  4,  6,  7,  9])

In [98]:
b[0]

2

In [99]:
b[0]=2000  # also change in arr4

In [100]:
b

array([2000,    3,    5,    7,   56,    4,    6,    7,    9])

In [101]:
arr4         

array([2000,    3,    5,    7,   56,    4,    6,    7,    9])

In [103]:
c=arr4

In [104]:
c

array([2000,    3,    5,    7,   56,    4,    6,    7,    9])

In [105]:
arr4

array([2000,    3,    5,    7,   56,    4,    6,    7,    9])

In [106]:
c[1]

3

In [110]:
c[1]=456789  #shallow copy created here,,so c also point to the same location of the variable/pointer a

In [108]:
c

array([  2000, 456789,      5,      7,     56,      4,      6,      7,
            9])

In [109]:
arr4      

array([  2000, 456789,      5,      7,     56,      4,      6,      7,
            9])

#### numpy matrix library

In [111]:
import numpy.matlib as nm

In [112]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [120]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [121]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### linear algebra

In [21]:
arr5=np.array([[1,4],[6,2]])
arr6=np.array([[3,2],[3,1]])

In [129]:
arr5

array([[1, 4],
       [6, 2]])

In [130]:
arr6

array([[3, 2],
       [3, 1]])

In [132]:
arr5.dot(arr6)      # matrix multiply

array([[15,  6],
       [24, 14]])

In [133]:
arr5@arr6           # maatrix multiply

array([[15,  6],
       [24, 14]])

In [13]:
arr7=np.array([2,4,75,5,3,7,9])

In [14]:
np.flip(arr7)     #Reverse the order of elements in an array along the given axis.

array([ 9,  7,  3,  5, 75,  4,  2])

In [16]:
arr7

array([ 2,  4, 75,  5,  3,  7,  9])

In [17]:
np.argsort(arr7)    # Returns the indices that would sort an array.

array([0, 4, 1, 3, 5, 6, 2], dtype=int64)

In [19]:
np.argmax(arr7)   #Returns the indices of the maximum values along an axis.

2

In [22]:
arr5

array([[1, 4],
       [6, 2]])

In [23]:
arr6

array([[3, 2],
       [3, 1]])

In [25]:
np.multiply(arr5, arr6)  #  Multiply arguments element-wise.

array([[ 3,  8],
       [18,  2]])

In [26]:
arr5*arr6

array([[ 3,  8],
       [18,  2]])