In [1]:
# library>> collection of mokules and package
# numpy>> numeric python
# 2005 by travis oliphant

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
# numpy code is written in c++ so it is very fast

In [6]:
lis=[1,2,3,4, 3+5j, 'pankaj', 'bijay']
type(lis)

list

In [7]:
# numpy stores the data in an array
# an array is a container to store the data of same type

In [8]:
# why numpy: 
# due to array>> computation becomes fast(homogenious), continuous memory allocaiton

In [9]:
l=[1,2,3,4]

In [11]:
arr=np.array(l)

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.ndim

1

In [19]:
l=[1,2,3,4, 'pankaj', 'ram']  

In [20]:
np.array(l)   # dtype='<U11' assike code for datatype

array(['1', '2', '3', '4', 'pankaj', 'ram'], dtype='<U11')

In [24]:
arr1=np.array([[2,3,4], [4,5,6]])

In [26]:
arr1.ndim  # no of square breakts=dimension

2

In [27]:
arr1.shape

(2, 3)

In [29]:
mat=np.matrix([1,2,34])

In [30]:
mat

matrix([[ 1,  2, 34]])

In [31]:
type(mat)

numpy.matrix

In [33]:
arr2=np.array([[[1,2], [3,4]]])

In [34]:
arr2.ndim

3

In [35]:
arr3=np.array([[[[[1,2], [3,4]]]]])

In [36]:
arr3.ndim

5

In [37]:
l=[1,2,3,4]
np.asarray([1,2,3])

array([1, 2, 3])

In [38]:
np.asarray(mat)

array([[ 1,  2, 34]])

In [39]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [40]:
np.asanyarray(mat)  # can't convert in matrix to array

matrix([[ 1,  2, 34]])

In [41]:
t=([1,2,3], [4,5,6])

In [42]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr=np.asanyarray(t)

In [45]:
l=[1,2,3,4]

In [46]:
arr=np.array(l)

In [47]:
arr

array([1, 2, 3, 4])

In [48]:
arr[0]

1

In [49]:
arr[0]=100

In [50]:
arr

array([100,   2,   3,   4])

In [51]:
# imp for interview

# how array is different from list
# is arrya mutable>>> yes
# what is different bw deep and shallow copy

In [52]:
arr

array([100,   2,   3,   4])

In [53]:
arr=np.array([1,2,3,4])

In [54]:
arr

array([1, 2, 3, 4])

In [56]:
a=arr   # shallow copy  >> same memory loction

In [57]:
arr

array([1, 2, 3, 4])

In [58]:
arr[0]=1000

In [59]:
arr

array([1000,    2,    3,    4])

In [60]:
a

array([1000,    2,    3,    4])

In [61]:
arr=np.array([1,2,3,4])

In [62]:
arr

array([1, 2, 3, 4])

In [63]:
a=arr.copy()  # deep copy>> different memory location

In [64]:
a

array([1, 2, 3, 4])

In [65]:
arr[1]=5000

In [66]:
arr

array([   1, 5000,    3,    4])

In [67]:
a

array([1, 2, 3, 4])

In [68]:
# multiple ways to generate array

In [71]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [72]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [73]:
for i in range(5): 
    print(i)

0
1
2
3
4


In [75]:
iterable=(i for i in range(5))

In [76]:
iterable

<generator object <genexpr> at 0x000002094B4617D0>

In [77]:
next(iterable)

0

In [86]:
a=np.fromiter(iterable, float)

In [87]:
a

array([], dtype=float64)

In [83]:
np.fromstring('11 23 24', sep=' ')

array([11., 23., 24.])

In [85]:
np.fromstring('11,23,24', sep=',')

array([11., 23., 24.])

In [93]:
string='Ajay, Bijay, Sanjay'
np.array(string.split(','))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

In [94]:
range(10)  # this is iterable object

range(0, 10)

In [96]:
for i in range(10): 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [97]:
type(range(10))

range

In [98]:
next(range(10))

TypeError: 'range' object is not an iterator

In [99]:
a=iter(range(10))

In [100]:
next(a)

0

In [101]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [102]:
np.zeros(3)

array([0., 0., 0.])

In [106]:
a=np.zeros((2,3))

In [107]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
a.ndim

2

In [109]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [110]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
np.zeros([4])

array([0., 0., 0., 0.])

In [112]:
np.zeros(4)

array([0., 0., 0., 0.])

In [113]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [115]:
np.twos((3,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [118]:
np.zeros((3,4))  #2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
np.zeros((1,3,4))   # 3D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [121]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [122]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [123]:
arr=np.zeros((1,2,2,3,4))

In [124]:
arr.shape

(1, 2, 2, 3, 4)

In [125]:
arr.ndim

5

In [126]:
arr=np.ones((3,4))

In [127]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [129]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [130]:
arr-1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
arr/3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [132]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [133]:
np.random

<module 'numpy.random' from 'C:\\Users\\91830\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\random\\__init__.py'>

In [137]:
np.random.random_sample()   #and <1

0.3703500477556384

In [139]:
np.random.random_sample((5,))

array([0.83117509, 0.47925805, 0.79689114, 0.6779483 , 0.44588836])

In [141]:
np.random.rand(1)

array([0.89566389])

In [142]:
np.random.rand(2,3)

array([[0.76273027, 0.01583318, 0.57124478],
       [0.25592208, 0.3862916 , 0.64182539]])

In [147]:
arr=np.random.randint(1,5, size=(3,4))

In [148]:
arr.ndim

2

In [149]:
arr.shape

(3, 4)

In [150]:
# reshaping

arr

array([[3, 2, 4, 3],
       [1, 4, 2, 4],
       [4, 3, 2, 3]])

In [151]:
arr.reshape(2,6)

array([[3, 2, 4, 3, 1, 4],
       [2, 4, 4, 3, 2, 3]])

In [153]:
arr.reshape(4,-2343)

array([[3, 2, 4],
       [3, 1, 4],
       [2, 4, 4],
       [3, 2, 3]])

In [154]:
arr.reshape(-4234,6)

array([[3, 2, 4, 3, 1, 4],
       [2, 4, 4, 3, 2, 3]])

In [157]:
arr.reshape(-4234,6).base

array([[3, 2, 4, 3],
       [1, 4, 2, 4],
       [4, 3, 2, 3]])

In [158]:
arr.reshape(1,2,2,3)

array([[[[3, 2, 4],
         [3, 1, 4]],

        [[2, 4, 4],
         [3, 2, 3]]]])

In [159]:
arr1

array([[2, 3, 4],
       [4, 5, 6]])

In [160]:
arr

array([[3, 2, 4, 3],
       [1, 4, 2, 4],
       [4, 3, 2, 3]])

In [161]:
arr>2

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [ True,  True, False,  True]])

In [162]:
arr[arr>2]

array([3, 4, 3, 4, 4, 4, 3, 3])

In [170]:
arr1=np.random.randint(1,10, size=(5,6))

In [174]:
arr1[0][4]

3

In [176]:
arr1

array([[7, 1, 4, 8, 3, 1],
       [5, 4, 6, 6, 3, 6],
       [7, 6, 4, 2, 6, 8],
       [4, 2, 9, 5, 7, 2],
       [4, 6, 5, 9, 9, 8]])

In [175]:
arr1[0:3]

array([[7, 1, 4, 8, 3, 1],
       [5, 4, 6, 6, 3, 6],
       [7, 6, 4, 2, 6, 8]])

In [177]:
arr1[0:3,[0,2]]

array([[7, 4],
       [5, 6],
       [7, 4]])

In [178]:
arr1[[0,2]]

array([[7, 1, 4, 8, 3, 1],
       [7, 6, 4, 2, 6, 8]])

In [179]:
arr1[0,2]

4

In [180]:
arr1

array([[7, 1, 4, 8, 3, 1],
       [5, 4, 6, 6, 3, 6],
       [7, 6, 4, 2, 6, 8],
       [4, 2, 9, 5, 7, 2],
       [4, 6, 5, 9, 9, 8]])

In [181]:
arr1[2:5, 0:2]

array([[7, 6],
       [4, 2],
       [4, 6]])

In [213]:
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,6,(3,3))

In [215]:
arr1

array([[3, 2, 3],
       [2, 1, 3],
       [2, 1, 1]])

In [214]:
np.squeeze(arr1)

array([[3, 2, 3],
       [2, 1, 3],
       [2, 1, 1]])

In [189]:
arr1

array([[2, 3, 2],
       [2, 3, 2],
       [1, 3, 3]])

In [190]:
arr2

array([[5, 3, 4],
       [5, 5, 4],
       [4, 1, 3]])

In [191]:
arr1/0

C:\Users\91830\AppData\Local\Temp\ipykernel_22212\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [192]:
arr1

array([[2, 3, 2],
       [2, 3, 2],
       [1, 3, 3]])

In [ ]:
arr

In [193]:
arr1.T

array([[2, 2, 1],
       [3, 3, 3],
       [2, 2, 3]])

In [195]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [197]:
arr1=np.random.randint(1,6,(3,3))
arr2=np.random.randint(1,6,(3,3))

In [198]:
arr1

array([[1, 3, 2],
       [1, 2, 4],
       [1, 5, 4]])

In [199]:
arr1.flatten() # convert into 1d

array([1, 3, 2, 1, 2, 4, 1, 5, 4])

In [200]:
arr1

array([[1, 3, 2],
       [1, 2, 4],
       [1, 5, 4]])

In [204]:
arr=np.array([1,2,3,4])

In [205]:
arr.ndim

1

In [206]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3, 4]])

In [208]:
a=np.expand_dims(arr, axis=1
            )

In [210]:
a

array([[1],
       [2],
       [3],
       [4]])

In [211]:
np.squeeze(a)  

array([1, 2, 3, 4])

In [212]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [218]:
d=np.array(['pw', 'sKill'])

In [219]:
d

array(['pw', 'sKill'], dtype='<U5')

In [220]:
np.char.upper(d)

array(['PW', 'SKILL'], dtype='<U5')

In [221]:
np.char.lower(d)

array(['pw', 'skill'], dtype='<U5')

In [222]:
np.char.capitalize(d)

array(['Pw', 'Skill'], dtype='<U5')

In [223]:
arr1

array([[3, 2, 3],
       [2, 1, 3],
       [2, 1, 1]])

In [224]:
np.sin(arr1)

array([[0.14112001, 0.90929743, 0.14112001],
       [0.90929743, 0.84147098, 0.14112001],
       [0.90929743, 0.84147098, 0.84147098]])

In [225]:
np.cos(arr1)

array([[-0.9899925 , -0.41614684, -0.9899925 ],
       [-0.41614684,  0.54030231, -0.9899925 ],
       [-0.41614684,  0.54030231,  0.54030231]])

In [226]:
np.log(arr1)

array([[1.09861229, 0.69314718, 1.09861229],
       [0.69314718, 0.        , 1.09861229],
       [0.69314718, 0.        , 0.        ]])

In [227]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.47712125],
       [0.30103   , 0.        , 0.47712125],
       [0.30103   , 0.        , 0.        ]])

In [228]:
np.exp(arr1)

array([[20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  2.71828183, 20.08553692],
       [ 7.3890561 ,  2.71828183,  2.71828183]])

In [229]:
np.power(arr1,3)

array([[27,  8, 27],
       [ 8,  1, 27],
       [ 8,  1,  1]], dtype=int32)

In [230]:
np.mean(arr1)

2.0

In [231]:
np.max(arr1)

3

In [232]:
np.var(arr1)

0.6666666666666666

In [233]:
import numpy.matlib as nm

In [234]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [235]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [236]:
arr1@arr2

array([[24, 28, 22],
       [17, 20, 16],
       [13, 14, 10]])

In [237]:
np.dot(arr1,arr2)

array([[24, 28, 22],
       [17, 20, 16],
       [13, 14, 10]])

In [238]:
arr1

array([[3, 2, 3],
       [2, 1, 3],
       [2, 1, 1]])

In [239]:
np.linalg.det(arr1)

1.9999999999999996

In [240]:
np.linalg.inv(arr1)

array([[-1. ,  0.5,  1.5],
       [ 2. , -1.5, -1.5],
       [-0. ,  0.5, -0.5]])

In [242]:
a=np.array([[7,5.3,-3], [3,-5,2], [5,3,-7]])

In [243]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [244]:
b=np.array([16,8,0])

In [245]:
b

array([16,  8,  0])

In [246]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])

In [249]:
round(2.492562, 1)

2.5

In [250]:
# for 1 d array using from func
np.fromfunction(lambda i: i**2, (5,),dtype=float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
# np.ix
# unravel_index
# np.all