### 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [2]:
import numpy as np

In [3]:
arr=np.array([0,1,2,3,4,5])

In [4]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

### 2. Given a NumPy array 'arr', check if its data type is float64.
              arr = np.array([1.5, 2.6, 3.7])

In [8]:
arr = np.array([1.5, 2.6, 3.7])

In [10]:
arr.dtype

dtype('float64')

### 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [14]:
arr=np.array([2+3j, 3-5j, -3j])

In [16]:
arr.dtype

dtype('complex128')

### 4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [28]:
arr=np.array([2,5,7,9,23,56])

In [29]:
arr

array([ 2,  5,  7,  9, 23, 56])

In [30]:
arr.dtype

dtype('int32')

In [35]:
arr=arr.astype(np.float32)

In [36]:
arr

array([ 2.,  5.,  7.,  9., 23., 56.], dtype=float32)

In [37]:
arr.dtype

dtype('float32')

### 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [38]:
arr=np.array([2.3, 5.6, 7.8, 4.5, 6.7,9])

In [39]:
arr.dtype

dtype('float64')

In [44]:
arr=arr.astype(np.float32)

In [45]:
arr.dtype

dtype('float32')

### 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [46]:
arr=np.random.randint(1,20,(3,4))

In [47]:
arr

array([[ 8, 11, 12, 15],
       [18,  7,  5, 19],
       [13,  2,  2, 19]])

In [48]:
def array_attributes(arr): 
    return arr.shape, arr.size, arr.dtype

In [49]:
array_attributes(arr)

((3, 4), 12, dtype('int32'))

### 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [50]:
arr

array([[ 8, 11, 12, 15],
       [18,  7,  5, 19],
       [13,  2,  2, 19]])

In [51]:
def array_dimension(arr): 
    return arr.ndim

In [52]:
array_dimension(arr)

2

### 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [53]:
arr

array([[ 8, 11, 12, 15],
       [18,  7,  5, 19],
       [13,  2,  2, 19]])

In [54]:
arr.itemsize

4

In [58]:
arr.nbytes    # give the total size of the array 4*12

48

In [59]:
def item_size_info(arr): 
    item_size=arr.itemsize
    total_size=arr.nbytes
    return item_size, total_size

In [60]:
item_size_info(arr)

(4, 48)

### 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
#### strides: The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis.<br>For example, we have to skip 4 bytes (1 value) to move to the next column, but 20 bytes (if 5 values in row) to get to the same position in the next row.

In [70]:
arr=np.random.randint(1, 10, (4,5))

In [76]:
arr

array([[6, 1, 3, 8, 4],
       [8, 6, 8, 2, 1],
       [7, 9, 1, 8, 6],
       [6, 7, 7, 7, 9]])

In [74]:
def array_strides(arr): 
    return arr.strides

In [75]:
array_strides(arr)

(20, 4)

### 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [77]:
arr

array([[6, 1, 3, 8, 4],
       [8, 6, 8, 2, 1],
       [7, 9, 1, 8, 6],
       [6, 7, 7, 7, 9]])

In [78]:
def shape_stride_relationship(arr): 
    return arr.shape, arr.strides

In [79]:
shape_stride_relationship(arr)

((4, 5), (20, 4))

### 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [80]:
np.zeros(4)

array([0., 0., 0., 0.])

In [83]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
def create_zeros_array(n): 
    return np.zeros(n)

In [85]:
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [87]:
create_zeros_array((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [90]:
def create_ones_matrix(rows, cols): 
    return np.ones((rows, cols))

In [91]:
create_ones_matrix(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [92]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [93]:
def generate_range_array(start, stop, step): 
    arr=np.arange(start, stop, step)
    return arr

In [94]:
generate_range_array(2,16,3)

array([ 2,  5,  8, 11, 14])

### 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [95]:
np.linspace(2.4, 5.6, 10)

array([2.4       , 2.75555556, 3.11111111, 3.46666667, 3.82222222,
       4.17777778, 4.53333333, 4.88888889, 5.24444444, 5.6       ])

In [96]:
def generate_linear_space(start, stop, num): 
    arr=np.linspace(start, stop, num)
    return arr

In [97]:
generate_linear_space(2.3, 5.6, 20)

array([2.3       , 2.47368421, 2.64736842, 2.82105263, 2.99473684,
       3.16842105, 3.34210526, 3.51578947, 3.68947368, 3.86315789,
       4.03684211, 4.21052632, 4.38421053, 4.55789474, 4.73157895,
       4.90526316, 5.07894737, 5.25263158, 5.42631579, 5.6       ])

### 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [100]:
def create_identity_matrix(n): 
    sq_mat=np.eye(n)
    return sq_mat

In [101]:
create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 16. Write a function that takes a Python list and converts it into a NumPy array.

In [102]:
lis=[1, 3, 5, 6, 23, 56, 34.6]

In [104]:
def list_to_array(l): 
    arr=np.array(l)
    return arr

In [105]:
list_to_array(lis)

array([ 1. ,  3. ,  5. ,  6. , 23. , 56. , 34.6])

### 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [111]:
arr=np.random.randint(2,32, 7)

In [112]:
arr

array([17,  5,  3, 10,  9, 29, 20])

In [114]:
a=arr.view()      # this is the way to create shallow copy 

In [115]:
arr[0]=50000

In [116]:
arr

array([50000,     5,     3,    10,     9,    29,    20])

In [117]:
a

array([50000,     5,     3,    10,     9,    29,    20])

### 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [135]:
arr1=np.random.randint(2,8,(2,3))
arr2=np.random.randint(2,8,(2,3))

In [136]:
arr1

array([[6, 6, 4],
       [5, 4, 5]])

In [137]:
arr2

array([[7, 2, 6],
       [6, 4, 2]])

In [139]:
np.concatenate([arr1, arr2], axis=0)

array([[6, 6, 4],
       [5, 4, 5],
       [7, 2, 6],
       [6, 4, 2]])

In [140]:
np.concatenate([arr1, arr2], axis=1)

array([[6, 6, 4, 7, 2, 6],
       [5, 4, 5, 6, 4, 2]])

In [143]:
def concatenates(arr1, arr2): 
    concat=np.concatenate([arr1, arr2])
    return concat

In [144]:
concatenates(arr1, arr2)

array([[6, 6, 4],
       [5, 4, 5],
       [7, 2, 6],
       [6, 4, 2]])

In [145]:
def concatenates(arr1, arr2): 
    concat=np.concatenate([arr1, arr2], axis=1)
    return concat

In [146]:
concatenates(arr1, arr2)

array([[6, 6, 4, 7, 2, 6],
       [5, 4, 5, 6, 4, 2]])

### 19. Create two NumPy arrays with different shapes and concatenate them horizontally using`numpy. concatenate`.

In [158]:
arr1=np.random.randint(1,8, (3,4))
arr2=np.random.randint(1,9,(3,6))

In [161]:
arr1

array([[1, 5, 2, 3],
       [6, 4, 6, 7],
       [7, 3, 3, 3]])

In [162]:
arr2

array([[6, 6, 1, 3, 4, 1],
       [7, 3, 4, 3, 6, 2],
       [7, 3, 8, 2, 5, 3]])

In [159]:
np.concatenate([arr1, arr2], axis=1)

array([[1, 5, 2, 3, 6, 6, 1, 3, 4, 1],
       [6, 4, 6, 7, 7, 3, 4, 3, 6, 2],
       [7, 3, 3, 3, 7, 3, 8, 2, 5, 3]])

### 20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [1]:
import numpy as np

In [24]:
arr1=np.random.randint(1,8, (3,4))
arr2=np.random.randint(1,8, (3,4))

In [29]:
def v_stack(arr1, arr2): 
    vs=np.vstack((arr1, arr2))
    return vs

In [30]:
v_stack(arr1, arr2)

array([[7, 5, 2, 3],
       [3, 7, 2, 5],
       [7, 5, 2, 4],
       [3, 3, 2, 6],
       [1, 7, 3, 5],
       [6, 4, 6, 3]])

In [17]:
arr1

array([[1, 2, 5, 4],
       [2, 2, 4, 6],
       [7, 3, 1, 3]])

In [18]:
arr2

array([[4, 2, 2, 4],
       [4, 3, 2, 6],
       [3, 2, 2, 4]])

In [19]:
np.vstack((arr1,arr2))   # just like con concatenate row wise (axis=0)

array([[1, 2, 5, 4],
       [2, 2, 4, 6],
       [7, 3, 1, 3],
       [4, 2, 2, 4],
       [4, 3, 2, 6],
       [3, 2, 2, 4]])

In [20]:
np.concatenate([arr1, arr2], axis=0)

array([[1, 2, 5, 4],
       [2, 2, 4, 6],
       [7, 3, 1, 3],
       [4, 2, 2, 4],
       [4, 3, 2, 6],
       [3, 2, 2, 4]])

### 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [58]:
def create_array(start, stop, step): 
    arr=np.arange(start,stop+1, step, dtype=int) # for inclusive stop+1
    return arr

In [62]:
create_array(1, 10, 3)

array([ 1,  4,  7, 10])

### 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


In [63]:
def gen_arr(): 
    arr=np.linspace(0,1,10)  #  by defalult[0,1](inclusive)
    return arr

In [65]:
gen_arr()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [67]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

### 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [87]:
def gen_arr(start, stop,num): 
    arr=np.logspace(np.log10(start), np.log10(stop),num)
    return arr

In [88]:
gen_arr(1,100,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [96]:
import pandas as pd

In [100]:
df=pd.DataFrame(np.random.randint(1,100,(5,3) ))

In [101]:
df

0   1   2
0  57  58  37
1  38  22  22
2  10  32  31
3  62  57  43
4  70  38  19

In [102]:
type(df)

pandas.core.frame.DataFrame

### 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [3]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(np.random.randint(-50,50,(5,3) ))

In [7]:
df

0   1   2
0 -35  47   5
1 -39 -12  31
2  19 -10  18
3  21  33  39
4  30 -30  32

In [8]:
df.dtypes

0    int32
1    int32
2    int32
dtype: object

In [ ]:
def replace_neg(df): 
    

In [ ]:



26. Access the 3rd element from the given NumPy array.

               arr = np.array([10, 20, 30, 40, 50])

27. Retrieve the element at index (1, 2) from the 2D NumPy array.

                 arr_2d = np.array([[1, 2, 3],
                                    [4, 5, 6],
                                    [7, 8, 9]])



28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

                        arr = np.array([3, 8, 2, 10, 5, 7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
                        arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
                     arr_2d = np.array([[1, 2, 3],
                                        [4, 5, 6],
                                        [7, 8, 9]])